/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soongsil_alopeciadetect_views_ProcessActivity_PagerAdapterClass */

#ifndef _Included_com_soongsil_alopeciadetect_views_ProcessActivity_PagerAdapterClass
#define _Included_com_soongsil_alopeciadetect_views_ProcessActivity_PagerAdapterClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
