/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soongsil_alopeciadetect_views_ProcessActivity */

#ifndef _Included_com_soongsil_alopeciadetect_views_ProcessActivity
#define _Included_com_soongsil_alopeciadetect_views_ProcessActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soongsil_alopeciadetect_views_ProcessActivity
 * Method:    AddrToMat
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_soongsil_alopeciadetect_views_ProcessActivity_AddrToMat
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
