/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soongsil_alopeciadetect_views_PictureActivity */

#ifndef _Included_com_soongsil_alopeciadetect_views_PictureActivity
#define _Included_com_soongsil_alopeciadetect_views_PictureActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soongsil_alopeciadetect_views_PictureActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_soongsil_alopeciadetect_views_PictureActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_soongsil_alopeciadetect_views_PictureActivity
 * Method:    Segmentation
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_soongsil_alopeciadetect_views_PictureActivity_Segmentation
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_soongsil_alopeciadetect_views_PictureActivity
 * Method:    MorphologyOpening
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_soongsil_alopeciadetect_views_PictureActivity_MorphologyOpening
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_soongsil_alopeciadetect_views_PictureActivity
 * Method:    MorphologyClosing
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_soongsil_alopeciadetect_views_PictureActivity_MorphologyClosing
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_soongsil_alopeciadetect_views_PictureActivity
 * Method:    IsKeratin
 * Signature: (JJ)V
 */
JNIEXPORT int JNICALL Java_com_soongsil_alopeciadetect_views_PictureActivity_IsKeratin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_soongsil_alopeciadetect_views_PictureActivity
 * Method:    CanyEdgeDetect
 * Signature: (JJIII)V
 */
JNIEXPORT void JNICALL Java_com_soongsil_alopeciadetect_views_PictureActivity_CanyEdgeDetect
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
