/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soongsil_alopeciadetect_MainActivity */

#ifndef _Included_com_soongsil_alopeciadetect_MainActivity
#define _Included_com_soongsil_alopeciadetect_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soongsil_alopeciadetect_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_soongsil_alopeciadetect_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_soongsil_alopeciadetect_MainActivity
 * Method:    IsKeratin
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_soongsil_alopeciadetect_MainActivity_IsKeratin
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_soongsil_alopeciadetect_MainActivity
 * Method:    IsAlopecia
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_soongsil_alopeciadetect_MainActivity_IsAlopecia
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
